export const CHANGE_BACKGROUND_START = 'CHANGE_BACKGROUND_START';
export const CHANGE_BACKGROUND_SUCCESS = 'CHANGE_BACKGROUND_SUCCESS';
export const CHANGE_BACKGROUND_FAILED = 'CHANGE_BACKGROUND_FAILED';

export const GET_WEATHER_START = 'GET_WEATHER_START';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILED = 'GET_WEATHER_FAILED';
